import pytest

class TestCSSVerification:
    """Tests for get_verified_css_selector.

    These tests require Chrome running with --remote-debugging-port=9222.
    Mark as skip if CDP is not available.
    """

    @pytest.fixture(autouse=True)
    def check_cdp(self):
        from actionshot.cdp import ChromeCDP
        cdp = ChromeCDP()
        if not cdp.is_available():
            pytest.skip("CDP not available")

    def test_autogenerated_id_detection(self):
        from actionshot.cdp import ChromeCDP
        cdp = ChromeCDP()
        assert cdp._is_autogenerated_id("a1b2c3d4-e5f6-7890-abcd-ef1234567890") is True
        assert cdp._is_autogenerated_id("12345") is True
        assert cdp._is_autogenerated_id("__react_component_1") is True
        assert cdp._is_autogenerated_id("ng-app-root") is True
        assert cdp._is_autogenerated_id("a") is True  # too short
        assert cdp._is_autogenerated_id("txtUsuario") is False
        assert cdp._is_autogenerated_id("btnEntrar") is False
        assert cdp._is_autogenerated_id("main-content") is False
